[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flet-mvp"
version = "1.0"
requires-python = ">=3.10"
dependencies = ["typer[all]", "copier"]

[project.scripts]
flet-mvp = "cli.cli:app"